---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  description: Central postgresql cluster
  # renovate: datasource=docker depName=ghcr.io/tensorchord/vchord-postgres
  imageName: ghcr.io/tensorchord/vchord-postgres:pg18-v1.1.0
  instances: 3
  affinity:
    enablePodAntiAffinity: true #default value
    topologyKey: kubernetes.io/hostname #default value
    podAntiAffinityType: required #default value
  storage:
    size: 50Gi
    storageClass: longhorn-basic
    resizeInUseVolumes: true
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
    parameters:
      max_connections: "200"
      shared_buffers: 256MB
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  superuserSecret:
    name: cloudnative-pg-secret
  enableSuperuserAccess: true
  env:
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: cloudnative-pg-secret
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: cloudnative-pg-secret
        key: AWS_SECRET_ACCESS_KEY
  - name: AWS_REGION
    valueFrom:
      secretKeyRef:
        name: cloudnative-pg-secret
        key: AWS_REGION
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters: &pluginparams
        barmanObjectName: k8s-postgres
        serverName: postgres
  externalClusters:
    - name: source
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters: *pluginparams
  resources:
    requests:
      cpu: 500m
    limits:
      hugepages-2Mi: 1Gi
      memory: 2Gi
  monitoring:
    enablePodMonitor: true
