---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudnative-pg-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "{{ .POSTGRES_SUPER_USER }}"
        password: "{{ .POSTGRES_SUPER_PASS }}"
        AWS_ACCESS_KEY_ID: "{{ .K8S_POSTGRES_API_KEY }}"
        AWS_SECRET_ACCESS_KEY: "{{ .K8S_POSTGRES_API_SECRET }}"
        AWS_REGION: "{{ .S3_REGION }}"

  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: intercolo
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authentik-db-credentials
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "{{ .AUTHENTIK_POSTGRESQL_USER }}"
        password: "{{ .AUTHENTIK_POSTGRESQL_PASSWORD }}"

  dataFrom:
    - extract:
        key: authentik
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-db-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "{{ .PAPERLESS_DBUSER }}"
        password: "{{ .PAPERLESS_DBPASS }}"
  dataFrom:
    - extract:
        key: paperless
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: nextcloud-db-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "{{ .NEXTCLOUD_POSTGRESQL_USERNAME }}"
        password: "{{ .NEXTCLOUD_POSTGRESQL_PASSWORD }}"
  dataFrom:
    - extract:
        key: nextcloud
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: open-webui-db-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "{{ .OPENWEBUI_DB_USER }}"
        password: "{{ .OPENWEBUI_DB_PASS }}"
  dataFrom:
    - extract:
        key: openwebui
