apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:k1Lo2MiLJhyplSP0tLB8H4B70sz8csxinyFcsVqTUGKxcMPaKFJIzw==,iv:fSbRg425AXgoe0YClF8kIsTK6ftO24qNmtzvH91uOG4=,tag:/qOq7iSXbkgkGdqH2eFFUg==,type:str]
sops:
  age:
    - recipient: age16gpqg7ku5tm5m0g09s50wtj3ahyqq4shmv5q2efdv8f25wynqefqen7vyx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHU0txTkdhWU9uVkF1R2Qr
        WjBzU0JpVEJrSXdyYzZsVWFXR0xhelQyV1VRCjBkYmxZcEM4OUh5a1BodldXU01O
        VkhKWHgyZzhUWG5qdDE1REptRnB0VFUKLS0tIElENTlkdjJGcUxDN3pHQ1k4UjBp
        eS9BcXQzVXhqUjBMenJtRkVpdWR2YUkK7sBIYj+xiFTyQgZ5LaIEqMaYsVfuzX5T
        J0JqkvpGDljpQPXYaA1MJc1sC4osbEIMO9JZT4oYYyN8IFfpsOWe6Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T16:46:20Z"
  mac: ENC[AES256_GCM,data:Zo1BT4Zq1enyIXZCmHU8aB7xcqr4MWl5VoqQoP76MynQKY2NGluuKY8SZi556TbYvd1jOcd24aM1jZbSK/R6IbR1WBjnk/iUZUCbNd2FiyK5GxoUtguWsbxffcUzOvuWNd7MSSJetUK2LqVJNRok8Mh+Fo71HsFKk6085oUzB2Q=,iv:bczuxSecofV6IzQgVQQI5evUD9eX8P6TdQk2Efcd1u8=,tag:byzx6JCnOwRlE53GpooviQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
