apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:D9Az6a6MGQq1EQ==,iv:4ZN0b6tAQgpZzyRPiKJbHQFVq6k1bJ3guy6Mb3KvzI0=,tag:kWueoCRfLHk1/Of2r6HNQA==,type:str]
    SECRET_MAIL_SERVER: ENC[AES256_GCM,data:FUtJZm2MgVYqUvXg,iv:+j662AMW3gWgDoHvMq6Ur2BWQZDO+Dh5McJIcnb3Pyk=,tag:aoAnHhN4jKaGQVeQQrPA6w==,type:str]
sops:
    age:
        - recipient: age16gpqg7ku5tm5m0g09s50wtj3ahyqq4shmv5q2efdv8f25wynqefqen7vyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNjlIREZrdzFKMnNXcmc3
            MU1FRXBqWWl2STRVNmw1cjNuaXk2RytVWkdRCnEvWmZ6eXZXc29Ja0d6RlNPcllM
            ZFRHUm0ySkxCWlBCMmR1NnBsR3Rma0EKLS0tIFJ3cmprcU81Y29hU0tSc1Q3M01U
            ZWtqYUpZeTBjU0hWcE8zL05zUnROTWsK2/l8JJ9xCmc7SF9tI0CQieqfl1+AxAVT
            39kD/oyqk9hvVyTzPlXlCDVRNO19r3P8zZySm4cG5chFWKLLtYDFJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T12:32:07Z"
    mac: ENC[AES256_GCM,data:+MzP0nC9YTvxS007rDRzHo9QPv8wPLiH2R366ABhcI6Hs5EcFAzd9Hrif1LnWKtIMXe4jq/+lwLjDxiPoFT3lNEI520X6pp26jTBjMM4PvvAU4TVihHWq4jHTDcTGFUcNi9gMe/VXQNoIu9NRMfnV1t1TiBnRWBVOnYohCu1rlA=,iv:RVEfGhOHCXqcS0VOBoc3aVnf52373CIpnILKo6Z3J9U=,tag:VmE/OmQmhekpIjMNJQaVCw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
