apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:D9Az6a6MGQq1EQ==,iv:4ZN0b6tAQgpZzyRPiKJbHQFVq6k1bJ3guy6Mb3KvzI0=,tag:kWueoCRfLHk1/Of2r6HNQA==,type:str]
sops:
  age:
    - recipient: age16gpqg7ku5tm5m0g09s50wtj3ahyqq4shmv5q2efdv8f25wynqefqen7vyx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNjlIREZrdzFKMnNXcmc3
        MU1FRXBqWWl2STRVNmw1cjNuaXk2RytVWkdRCnEvWmZ6eXZXc29Ja0d6RlNPcllM
        ZFRHUm0ySkxCWlBCMmR1NnBsR3Rma0EKLS0tIFJ3cmprcU81Y29hU0tSc1Q3M01U
        ZWtqYUpZeTBjU0hWcE8zL05zUnROTWsK2/l8JJ9xCmc7SF9tI0CQieqfl1+AxAVT
        39kD/oyqk9hvVyTzPlXlCDVRNO19r3P8zZySm4cG5chFWKLLtYDFJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T16:46:20Z"
  mac: ENC[AES256_GCM,data:yNMuhysaGum/zpIenxr9DgXTyEFrjRAZffRqzDsDj6y8Lc4pBTDgcOBW5F8XsnEiJM24qGZzVFn7COv8Svt07bgY8w9HGMcESyLjhi/dnTb/3nRNa9PvNjybBm9C5rNrB5jG9gTdNPPZHJLyreHL3PE0jgMy/+lZsatSFfNCwxM=,iv:BCQ6v4yLcS1JRL/HNv+wMTRgrqUnVGn8fHAUlbT4LZ8=,tag:vXBy7TMGK3q3BNDcFnpCCw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
