apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:D9Az6a6MGQq1EQ==,iv:4ZN0b6tAQgpZzyRPiKJbHQFVq6k1bJ3guy6Mb3KvzI0=,tag:kWueoCRfLHk1/Of2r6HNQA==,type:str]
    SECRET_MAIL_SERVER: ENC[AES256_GCM,data:FUtJZm2MgVYqUvXg,iv:+j662AMW3gWgDoHvMq6Ur2BWQZDO+Dh5McJIcnb3Pyk=,tag:aoAnHhN4jKaGQVeQQrPA6w==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:IcXHWdpSc+GJMagz0g==,iv:zTDZzHJ2bfVpxtHZbnl11Nyac2EQnKca0Iml2Xi6DtA=,tag:2C1Zjb/UbLZYS+hPxIq9gQ==,type:str]
    DRAGONFLY_PASSWORD: ENC[AES256_GCM,data:siEfNWcZfAjg4s0iT5O1Drf6g/6qBeNHX7LcOPnU9DenyKx/U+oYa3NeYuQRApgtbBE=,iv:+SN+dd41A52+uIx5Vn1dymYm5fCs5T0JUkk9LCqCrQw=,tag:TG5dc1DmvpjwxLP6iNWwBw==,type:str]
    PAPERLESS_OPENID_CLIENT_ID: ENC[AES256_GCM,data:2HgYLx5/uE7xUOgf9bAyiJNsoMr8cFDHBqddDV9XlUuWSY+ehqpLPw==,iv:YoWtEGU5fN6+b8+YIni5e8IUoLAXtIevqgMRwSKseGo=,tag:VTBEp5GuwIbSv1hzcQ+13w==,type:str]
    PAPERLESS_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:X8hOSFylzt/LdPgCv44U5EbLW+qD92aHp5gQK27xSgA1em/+eFXsGxFF17FqkLniVvoQfJmn+Ep5bUG1ZBhEM8K/OCQB6KZ90nZIz8OSZ61xrUBx6vEcQX/Y4QrIA28dD31Avy1NaLZ7KTeHEm+HEYAl9efzO7aLffiHqWK/26M=,iv:1EDkf5HOyg7cC33H1P6jmgotPmHCblCfEGT/jKYjPLc=,tag:JQYd1Z/hosrArc/ozEJaUg==,type:str]
    NEXTCLOUD_OPENID_CLIENT_ID: ENC[AES256_GCM,data:4k9TkIlGASrRx4/f+p1zcgXy45r7AvejSHB7d2c8oDTvIpoetaDO/w==,iv:cG3kHCxCG6RPOcqcdU9MCNr4BkzvPWWdheJXaa+PEWo=,tag:g3YHoXJSUiuAZCp0QqqMBw==,type:str]
    NEXTCLOUD_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:7oJVKOdJJs7wn/20hVEC6mTYtZ4YkgMBKiai5Nhn3cLfEZHeMPRJXli/AWaBBXQRlSnswTByx0OBs4Q8vk43TMqmg/Lcztub5q9wmpH3UnS7SjXoACOYPCgtF89qntr+fKyUnVhgWUdnxWgv0Ipnh+2w23kWSLEEBu+7GZrrWRY=,iv:J5Ea7HFWcmKPHHSTUgn/1ifhh7aWSVtqTadPYZxgAiY=,tag:UUmy7GkmywKKRJJd3ilN+A==,type:str]
sops:
    age:
        - recipient: age16gpqg7ku5tm5m0g09s50wtj3ahyqq4shmv5q2efdv8f25wynqefqen7vyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNjlIREZrdzFKMnNXcmc3
            MU1FRXBqWWl2STRVNmw1cjNuaXk2RytVWkdRCnEvWmZ6eXZXc29Ja0d6RlNPcllM
            ZFRHUm0ySkxCWlBCMmR1NnBsR3Rma0EKLS0tIFJ3cmprcU81Y29hU0tSc1Q3M01U
            ZWtqYUpZeTBjU0hWcE8zL05zUnROTWsK2/l8JJ9xCmc7SF9tI0CQieqfl1+AxAVT
            39kD/oyqk9hvVyTzPlXlCDVRNO19r3P8zZySm4cG5chFWKLLtYDFJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T12:19:40Z"
    mac: ENC[AES256_GCM,data:LGe9JRM+d7jw1RuvIZF29L24yC8Cg7luPTFjKWOnBji0G6WbbzDPn8wbeocFbTjo0XNkfJJFOZ6NxrRZ28LQ7vwcKPdMfaZTiE+wxi6LyreaJBxteLUJCvAUhZyGbQAinNhydYKR5Ppvg7MNEZOoRBBmLdEJtinR0tplt7Zsfrw=,iv:kGHZEDXc2/p4gBcfEtIeUe2ngElylhy3euO4HgkK9dM=,tag:uAJvnuIeND5t69FDA4UY9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
