apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Qz34vGCYhwZnjx3YoiAc+uBvYvJgWwuE/X8+Py9AII8=,iv:AhQEqzOylp0tK3Rcd9OA8GzSuzU0rE9AkyY76fpMmFc=,tag:uW8roJfSd+3Df66xJ3iddw==,type:str]
sops:
  age:
    - recipient: age16gpqg7ku5tm5m0g09s50wtj3ahyqq4shmv5q2efdv8f25wynqefqen7vyx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNmE4V3ZiNTNQNDladU9G
        N3I1K2ZmdVVIS2hvQ1orY1AzZ1JiRzF0UkhNCjVrTnQzNWFkQWdROGl1NTFBcjRX
        ZS9sdzdBRkFuNTBEeGJOZnh2SGpFbEkKLS0tIGVLMlo2R3pXWXZMVmMxaGdNNmFR
        YTR5M21kckFBVHhZNUNpaGJBcU03eWcKqSn9L8Y2AbmELavUB+NEvuBl3I1q/hvT
        HcZtD4N3sQ+DMnCU7Cr6rXw+EoQB4i/br83xsx39ts7pDjg9+350mg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T16:46:20Z"
  mac: ENC[AES256_GCM,data:ZUseAW3Se9VEIdfctV+bnSY9HbIgMtmBNv1SjeBY7j9Dovu1lrVEI49NVVzilIIh1xM3vq2gGTpozXb+bR8OnCOTeZolfumJ9OUp0El28lJL2F2XCCa9IcfcOUXYhIwW447YHYi00MUkEHUcbkUrrMb+FXZ/vFwxus+oXN+Mbsg=,iv:yvkfsmIW7zHNdZzLUWJAxA+u8c9Jtdtzx2ul5CKGrRk=,tag:pF/TVbjIsNRVhPeefjmw1w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
