apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:rDTsJNhT75VgBpy8yxaXjANiIZWP4rm8zeDzwyhi7ONmUBacr6QFZwklc7SD/P8sKnf9EAfQz0UxcrYpoQ61beTdpqKFATHDdgck/BO3dgNbKyGip6lH2edAcdk+sSbdzFSaO+yAVjF5t0zCNB0f6r/NX2Z1pR5KOxp7fCC11XTBwp67ckzPR2DUv+Jm3sVymlYIW4kgyYpjFUIdzGGppwdBi6FxCl09fWkHp1VI7YEmVDkk,iv:n105qR2V4fJMeXhOrV9ml2gRrTqTiLHl358PyA7obg4=,tag:altINbOs5/mWryXYsp2wXg==,type:str]
sops:
  age:
    - recipient: age16gpqg7ku5tm5m0g09s50wtj3ahyqq4shmv5q2efdv8f25wynqefqen7vyx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Tk0yanZ6K243WHM2d3F5
        MTJuTmlHcVh2T2ZHWEk2eGlpNjBnYzltL1J3CnpLQ080bzJ4dHd4b2lKUHB2WlFi
        ejRJT2FuR3lIN25ldm1TZktpR21EdjAKLS0tIFAzS1NwQjcwcWtCcTVIS2dLUzlT
        dm9lVCszYngzcFdFaGU3T25jdnpMTkEK4810AhvdkqcD8QEoFhrR1kEog3Gxc3kC
        VwyO164vCpYYH0TjIZLtPJvsaXa7jV5GLysAC87+CJe5v8qC2BmP8A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T16:46:20Z"
  mac: ENC[AES256_GCM,data:Y6aLVNN1tnVettfhR0lYaoFpco4I9jKaNBUzLaA11OQruLVcNFQBLehjKKF5DOPb729l0MiuBgTUcQ9I351qoemBaCs2sSm1bXSRkNOzW9qi1SsbX7AipuayoogtAqwJU10WRYiv5BKUURf73bGfqjDJpY5HRqiA2tQ68vPOLPQ=,iv:6jTOfT2pDi+Ig7Qy8EHx5FGGuhhk/Ej+H0v2jRBojno=,tag:Cn+BkW12ZSQDTVynAG51WQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
