---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app trivy-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: trivy-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: trivy-operator
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      registry: ghcr.io
      repository: aquasecurity/trivy-operator
      tag: 0.22.0
    operator:
      webhooks:
        admission:
          enabled: true
      logLevel: info
      # Scan all namespaces in the cluster
      namespaceSelector: {}
    trivy:
      image:
        registry: ghcr.io
        repository: aquasecurity/trivy
        tag: 0.52.0
      severity: "HIGH,CRITICAL"
      scanJobCompletionDeadlineSeconds: 300
    scanJob:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
    vulnerability:
      scanners:
        - trivy
      scanOnlyCurrentRevisions: true
    compliance:
      enabled: false
    rbac:
      create: true
    serviceAccount:
      create: true
      name: *app
