apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:8TZsSEkC8lH+XSV+zRqkRD/mbFJcSfNZk44Ks4/t241HlpIbADNPBQ==,iv:hAK7aLfFme0/k/NSMcvScGjI7pvg0446PpoftjaRjZ8=,tag:8p/WSuohTvBN3M9x/IF6YA==,type:str]
sops:
  age:
    - recipient: age16gpqg7ku5tm5m0g09s50wtj3ahyqq4shmv5q2efdv8f25wynqefqen7vyx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRWpReEE5bTIzcXVxMmNW
        cGFkdDlWcXpaNWJITTgyYTZiRndMbFFmWkdjClpaR3VxSFpOb2EyQ1RQWmtkQ0dP
        UTRnZDl6eHpaRWx0QUdxUC9QT213Q1kKLS0tIGRQcDYvL1FVSVlxQ2JZa2VyK1k5
        Nk4vY2NjRUlXOUtGRTd0c1pqTzF4SlkKC7ybF3nv+yJaXXUpR3oE9De2p2CEypNv
        N/lG1w7elM4x/xsWgplE+2Yodjk/G+vVSpyGFIrZVgbN5MdiHWW8KA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T16:46:20Z"
  mac: ENC[AES256_GCM,data:pIDMZdDoFO6es8xXvDcLABdcGJri1oxIqMwFdrmS/jxA/LCYv7MW9C7oe7kPidmKCQZuQd9neDjQtbVkH5oK2/RIjDZKIO7PqypmRjZARpCLg1beio8XhYs5Rq4dkhV9Q7W9WNy1Q6unkUdCTAiIGAX61Pelfq8haQm2En9gunI=,iv:jy8PLp9rI6PKGkwUtq+mS6IPfVI0SxwTnHdHESu3JxY=,tag:BaBLAzCSt3OYS2G399B/zA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
