---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-standard
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-basic
  resources:
    requests:
      storage: 5Gi
