apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-premium
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-consume-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-basic
  resources:
    requests:
      storage: 1Gi
