---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: openclaw-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OPENCLAW_GATEWAY_TOKEN: "{{ .OPENCLAW_GATEWAY_TOKEN }}"
        OPENROUTER_API_KEY: "{{ .OPENROUTER_OPENWEBUI_API_KEY }}"
        OPENCLAW_API_KEY: "{{ .OPENROUTER_OPENWEBUI_API_KEY }}"
        PAPERLESS_API_URL: "http://paperless-ngx.paperless.svc.cluster.local:80"
        PAPERLESS_API_TOKEN: "{{ .PAPERLESS_API_TOKEN }}"
        TELEGRAM_BOT_TOKEN: "{{ .TELEGRAM_BOT_TOKEN }}"
  dataFrom:
    - extract:
        key: openclaw
    - extract:
        key: openrouter
    - extract:
        key: paperless
