---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app openclaw
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    controllers:
      openclaw:
        replicas: 1
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
          secret.reloader.stakater.com/reload: "openclaw-secret"
        containers:
          app:
            image:
              repository: ghcr.io/openclaw/openclaw
              tag: 2026.2.26
            env:
              PORT: &port 3000
              TZ: ${TIMEZONE}
              OPENCLAW_STATE_DIR: /data/.openclaw
              OPENCLAW_WORKSPACE_DIR: /data/workspace
              NODE_OPTIONS: --max-old-space-size=2048
            envFrom:
              - secretRef:
                  name: openclaw-secret
            resources:
              requests:
                cpu: 100m
                memory: 1Gi
              limits:
                memory: 3Gi

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    route:
      app:
        hostnames:
          - claw.${SECRET_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port

    persistence:
      data:
        enabled: true
        existingClaim: openclaw-pvc
        advancedMounts:
          openclaw:
            app:
              - path: /data
                subPath: data
