---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: whiteboard
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: whiteboard-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        WHITEBOARD_JWT_SECRET_KEY: "{{ .WHITEBOARD_JWT_SECRET_KEY }}"

  dataFrom:
    - extract:
        key: cnextcloud
