---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: collabora
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: collabora-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        COLLABORA_USERNAME: "{{ .COLLABORA_USERNAME }}"
        COLLABORA_PASSWORD: "{{ .COLLABORA_PASSWORD }}"

  dataFrom:
    - extract:
        key: collabora
