apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcvloud-data-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-standard
  resources:
    requests:
      storage: 100Gi
